name: build
on:
  - push
  
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: install npm dependencies
        run: npm install
        
      - name: build extension
        run: npm run compile